Bind-mount /tmp into the chroot
apt pkgDPkgPM::Go() uses /tmp in order to pass some kind of data
when calling dpkg. But it is not smart enough to realise that
/tmp at this point will not be available when we call dpkg under
the chroot, resulting in this error:

Setting up install-info (6.3.0.dfsg.1-1bem2) ...
Chrooting into /root/master/
dpkg: error: cannot stat pathname '/tmp/apt-dpkg-install-xSlv1N': No such file or directory
E:Sub-process /usr/bin/dpkg returned an error code (2)
Traceback (most recent call last):
  File "/apt-bootstrap", line 490, in <module>
    bootstrap.bootstrap()
  File "/apt-bootstrap", line 428, in bootstrap
    self.stage2()
  File "/apt-bootstrap", line 405, in stage2
    self.cache.commit(fetch_progress=self.acquire_progress)
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 529, in commit
    raise SystemError("installArchives() failed")
SystemError: installArchives() failed

Bind-mount /tmp into the chroot so that it is shared, avoiding this
problem.